#!/bin/bash

sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged" \
           --add item spotify_indicator center \
           --set spotify_indicator background.color=$ACCENT_COLOR  \
           --set spotify_indicator background.height=21 \
           --set spotify_indicator background.padding_left=8 \
           --set spotify_indicator background.padding_right=8 \
           --set spotify_indicator icon=􀑪 \
           --set spotify_indicator icon.color=$ITEM_BG_COLOR \
           --set spotify_indicator icon.padding_left=5 \
           --set spotify_indicator icon.padding_right=3 \
           --set spotify_indicator label.color=$ITEM_BG_COLOR \
           --set spotify_indicator label.drawing=on \
           --set spotify_indicator label.padding_right=5 \
           --set spotify_indicator update_freq=2 \
           --set spotify_indicator script="$PLUGIN_DIR/spotify_indicator.sh" \
           --set spotify_indicator click_script="osascript -e 'tell application \"Spotify\" to activate'" \
           --add item spotify_prev center \
           --set spotify_prev drawing=on \
           --set spotify_prev icon.drawing=on \
           --set spotify_prev label.drawing=off \
           --set spotify_prev background.drawing=off \
           --set spotify_prev icon=􀊎 \
           --set spotify_prev icon.color=$WHITE \
           --set spotify_prev icon.font="SF Pro:Regular:14.0" \
           --set spotify_prev icon.padding_left=5 \
           --set spotify_prev icon.padding_right=3 \
           --set spotify_prev click_script="$PLUGIN_DIR/spotify_prev_click.sh" \
           --add item spotify_play center \
           --set spotify_play drawing=on \
           --set spotify_play icon.drawing=on \
           --set spotify_play label.drawing=off \
           --set spotify_play background.drawing=off \
           --set spotify_play icon=􀊄 \
           --set spotify_play icon.color=$WHITE \
           --set spotify_play icon.font="SF Pro:Regular:14.0" \
           --set spotify_play icon.padding_left=3 \
           --set spotify_play icon.padding_right=3 \
           --set spotify_play script="$PLUGIN_DIR/spotify_play.sh" \
           --set spotify_play update_freq=2 \
           --set spotify_play click_script="$PLUGIN_DIR/spotify_play_click.sh" \
           --add item spotify_next center \
           --set spotify_next drawing=on \
           --set spotify_next icon.drawing=on \
           --set spotify_next label.drawing=off \
           --set spotify_next background.drawing=off \
           --set spotify_next icon=􀊐 \
           --set spotify_next icon.color=$WHITE \
           --set spotify_next icon.font="SF Pro:Regular:14.0" \
           --set spotify_next icon.padding_left=3 \
           --set spotify_next icon.padding_right=5 \
           --set spotify_next click_script="$PLUGIN_DIR/spotify_next_click.sh" \
           --subscribe spotify_indicator spotify_change \
           --subscribe spotify_prev spotify_change \
           --subscribe spotify_play spotify_change \
           --subscribe spotify_next spotify_change \
           --update spotify_indicator \
           --update spotify_play